<?php
// Generated by Zend Framework 2
return array(
    'SpacedGAPRbac\Entity\Permission'               => __DIR__ . '/src/SpacedGAPRbac/Entity/Permission.php',
    'SpacedGAPRbac\Entity\PermissionAbstract'       => __DIR__ . '/src/SpacedGAPRbac/Entity/PermissionAbstract.php',
    'SpacedGAPRbac\Entity\Role'                     => __DIR__ . '/src/SpacedGAPRbac/Entity/Role.php',
    'SpacedGAPRbac\Entity\UserAbstract'             => __DIR__ . '/src/SpacedGAPRbac/Entity/UserAbstract.php',
    'SpacedGAPRbac\Entity\RoleAbstract'             => __DIR__ . '/src/SpacedGAPRbac/Entity/RoleAbstract.php',
    'SpacedGAPRbac\Entity\User'                     => __DIR__ . '/src/SpacedGAPRbac/Entity/User.php',
    'SpacedGAPRbac\Repository\UserRepository'       => __DIR__ . '/src/SpacedGAPRbac/Repository/UserRepository.php',
    'SpacedGAPRbac\Repository\PermissionRepository' => __DIR__ . '/src/SpacedGAPRbac/Repository/PermissionRepository.php',
    'SpacedGAPRbac\Repository\RoleRepository'       => __DIR__ . '/src/SpacedGAPRbac/Repository/RoleRepository.php',
    'SpacedGAPRbac\Module'                          => __DIR__ . '/src/SpacedGAPRbac/Module.php',
);