##
# SpacedGAPRbac\Entity\UserAbstract
##
SpacedGAPRbac\Entity\UserAbstract:
    type: mappedSuperclass
    repositoryClass: SpacedGAPRbac\Repository\UserRepository
    schema: public
    table: public.users

    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: AUTO
                    
    fields:
        username:
            type: string
            nullable: true
            length: 255
                
        email:
            type: string
            nullable: false
            length: 255
                
        display_name:
            type: string
            nullable: true
            length: 255

        password:
            type: string
            nullable: false
            length: 255

        state:
            type: integer
            nullable: true
            length: 255
